import { notFound } from "next/navigation";
import { fetchGitHubProfile } from "@/lib/github";
import { PortfolioHeader } from "@/components/Portfolio/PortfolioHeader";
import { ProjectsGrid } from "@/components/Portfolio/ProjectsGrid";
import { Highlights } from "@/components/Portfolio/Highlights";
import { Skills } from "@/components/Portfolio/SkillsChart";
import { ActivityGraph } from "@/components/Portfolio/ActivityGraph";
import { Achievements } from "@/components/Portfolio/Achievements";
import { AICoach } from "@/components/Portfolio/AICoach";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { ShareButton } from "@/components/ShareButton";
import { AnalyticsModal } from "@/components/Portfolio/AnalyticsModal";
import { ResumeButton } from "@/components/Portfolio/ResumeButton";
import { MintButton } from "@/components/Portfolio/MintButton";

export async function generateMetadata({ params }) {
  const { username } = await params;
  const data = await fetchGitHubProfile(username);

  if (!data) {
    return {
      title: "User Not Found - PortfolioAI",
      description: "The requested GitHub portfolio could not be found.",
    };
  }

  const { user } = data;
  const title = `${user.name || user.login} - Developer Portfolio`;
  const description = user.bio || `Check out ${user.login}'s developer portfolio generated by PortfolioAI.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [
        {
          url: user.avatar_url,
          width: 400,
          height: 400,
          alt: `${user.login}'s avatar`,
        },
      ],
      type: "profile",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [user.avatar_url],
      creator: user.twitter_username ? `@${user.twitter_username}` : undefined,
    },
  };
}

export default async function PortfolioPage({ params }) {
  const { username } = await params;
  const data = await fetchGitHubProfile(username);

  if (!data) {
    return notFound();
  }

  const { user, repos, stats } = data;

  return (
    <main className="min-h-screen bg-black text-white pb-20">
      <div className="fixed top-4 left-4 z-50">
        <Link href="/">
          <Button variant="ghost" size="sm" className="text-gray-400 hover:text-white">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
        </Link>
      </div>
      
      <div className="fixed top-4 right-4 z-50 flex gap-2">
        <AnalyticsModal />
        <ResumeButton username={username} />
        <MintButton />
        <ShareButton username={username} />
        <ThemeSwitcher defaultTheme={stats.suggestedTheme} />
      </div>

      <PortfolioHeader user={user} stats={stats} />
      
      <Highlights stats={stats} user={user} />

      <ActivityGraph />

      <Achievements achievements={stats.achievements} />

      <ProjectsGrid repos={repos} />
      
      <Skills languages={stats.topLanguages} topics={stats.topTopics} />
      
      <AICoach suggestions={stats.suggestions} />
      
      <footer className="text-center text-gray-600 py-8 text-sm">
        <p>Generated by GitHub Portfolio AI</p>
      </footer>
    </main>
  );
}
