"use client";

import { useState } from "react";
import { Share2, Copy, Twitter, Linkedin, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export function ShareButton({ username }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareText = `Check out my stunning developer portfolio generated by PortfolioAI! 🚀\n\nhttps://github-profile.vercel.app/portfolio/${username}`;

  const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
    shareText
  )}`;
  const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(
    `https://github-profile.vercel.app/portfolio/${username}`
  )}`;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="icon"
          className="rounded-full bg-white/5 border-white/10 hover:bg-white/10"
        >
          <Share2 className="w-5 h-5" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="end"
        className="bg-black/90 border-white/10 backdrop-blur-xl"
      >
        <DropdownMenuItem
          onClick={handleCopy}
          className="text-gray-300 hover:text-white hover:bg-white/10 cursor-pointer"
        >
          <div className="flex items-center gap-2">
            {copied ? (
              <Check className="w-4 h-4 text-green-500" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
            {copied ? "Copied!" : "Copy Link"}
          </div>
        </DropdownMenuItem>
        <DropdownMenuItem
          asChild
          className="text-gray-300 hover:text-white hover:bg-white/10 cursor-pointer"
        >
          <a
            href={twitterUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 w-full"
          >
            <Twitter className="w-4 h-4" />
            Share on Twitter
          </a>
        </DropdownMenuItem>
        <DropdownMenuItem
          asChild
          className="text-gray-300 hover:text-white hover:bg-white/10 cursor-pointer"
        >
          <a
            href={linkedinUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 w-full"
          >
            <Linkedin className="w-4 h-4" />
            Share on LinkedIn
          </a>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
